@startuml
actor "This is [[#alice{Alice tooltip} Alice]] actor" as Alice
actor "This is [[http://plantuml.com/sequence{Bob tooltip} Bob]] actor" as Bob

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml